/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_mainwindow (void)
{
  GtkWidget *mainwindow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *mgame;
  GtkWidget *mgame_menu;
  GtkAccelGroup *mgame_menu_accels;
  GtkWidget *mquit;
  GtkWidget *mprefs;
  GtkWidget *mprefs_menu;
  GtkAccelGroup *mprefs_menu_accels;
  GtkWidget *mtans;
  GtkWidget *mtans_menu;
  GtkAccelGroup *mtans_menu_accels;
  GtkWidget *mtanscolor;
  GtkWidget *mtanstexture;
  GtkWidget *mhitan;
  GtkWidget *mhitan_menu;
  GtkAccelGroup *mhitan_menu_accels;
  GtkWidget *mhighcolor;
  GtkWidget *mhightexture;
  GtkWidget *mbg;
  GtkWidget *mbg_menu;
  GtkAccelGroup *mbg_menu_accels;
  GtkWidget *mbgcolor;
  GtkWidget *mbgtexture;
  GtkWidget *mhlpoutcolor;
  GtkWidget *s_parateur1;
  GtkWidget *msilcolor;
  GtkWidget *msilbgcolor;
  GtkWidget *msilbgcol2;
  GtkWidget *mhlptancolor;
  GtkWidget *s_parateur2;
  GtkWidget *imsize;
  GtkWidget *imsize_menu;
  GtkAccelGroup *imsize_menu_accels;
  GtkWidget *msizinc;
  GtkWidget *msizdec;
  GtkWidget *maccuracy;
  GtkWidget *maccuracy_menu;
  GtkAccelGroup *maccuracy_menu_accels;
  GSList *accgrp_group = NULL;
  GtkWidget *maccuracy1;
  GtkWidget *maccuracy2;
  GtkWidget *maccuracy3;
  GtkWidget *rotstp;
  GtkWidget *rotstp_menu;
  GtkAccelGroup *rotstp_menu_accels;
  GSList *rotgrp_group = NULL;
  GtkWidget *mrotcont;
  GtkWidget *mrotstp;
  GtkWidget *separator1;
  GtkWidget *mfigfile;
  GtkWidget *s_parateur3;
  GtkWidget *msaveconf;
  GtkWidget *mmisc;
  GtkWidget *mmisc_menu;
  GtkAccelGroup *mmisc_menu_accels;
  GtkWidget *mabout;
  GtkWidget *mhelp;
  GtkWidget *sep17;
  GtkWidget *mclrstat;
  GtkWidget *mclrall;
  GtkWidget *table1;
  GtkWidget *aspectframe1;
  GtkWidget *wdrawareagrande;
  GtkWidget *aspectframe2;
  GtkWidget *wdrawareapetite;
  GtkWidget *vbox2;
  GtkWidget *hbox1;
  GtkWidget *label2;
  GtkObject *bfignr_adj;
  GtkWidget *bfignr;
  GtkWidget *hseparator2;
  GtkWidget *bunsel;
  GtkWidget *hseparator1;
  GtkWidget *bhlptan;
  GtkWidget *bhlpout;
  GtkWidget *wstatusbar;

  mainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (mainwindow, "mainwindow");
  gtk_object_set_data (GTK_OBJECT (mainwindow), "mainwindow", mainwindow);
  gtk_window_set_title (GTK_WINDOW (mainwindow), _("gTans"));
  gtk_window_set_default_size (GTK_WINDOW (mainwindow), 500, 430);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainwindow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar1, "menubar1");
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  mgame = gtk_menu_item_new_with_label (_("Game"));
  gtk_widget_set_name (mgame, "mgame");
  gtk_widget_ref (mgame);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mgame", mgame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mgame);
  gtk_container_add (GTK_CONTAINER (menubar1), mgame);

  mgame_menu = gtk_menu_new ();
  gtk_widget_set_name (mgame_menu, "mgame_menu");
  gtk_widget_ref (mgame_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mgame_menu", mgame_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (mgame), mgame_menu);
  mgame_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (mgame_menu));

  mquit = gtk_menu_item_new_with_label (_("Quit"));
  gtk_widget_set_name (mquit, "mquit");
  gtk_widget_ref (mquit);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mquit", mquit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mquit);
  gtk_container_add (GTK_CONTAINER (mgame_menu), mquit);

  mprefs = gtk_menu_item_new_with_label (_("Preferences"));
  gtk_widget_set_name (mprefs, "mprefs");
  gtk_widget_ref (mprefs);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mprefs", mprefs,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mprefs);
  gtk_container_add (GTK_CONTAINER (menubar1), mprefs);

  mprefs_menu = gtk_menu_new ();
  gtk_widget_set_name (mprefs_menu, "mprefs_menu");
  gtk_widget_ref (mprefs_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mprefs_menu", mprefs_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (mprefs), mprefs_menu);
  mprefs_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (mprefs_menu));

  mtans = gtk_menu_item_new_with_label (_("Tans"));
  gtk_widget_set_name (mtans, "mtans");
  gtk_widget_ref (mtans);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mtans", mtans,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mtans);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), mtans);

  mtans_menu = gtk_menu_new ();
  gtk_widget_set_name (mtans_menu, "mtans_menu");
  gtk_widget_ref (mtans_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mtans_menu", mtans_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (mtans), mtans_menu);
  mtans_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (mtans_menu));

  mtanscolor = gtk_menu_item_new_with_label (_("Color..."));
  gtk_widget_set_name (mtanscolor, "mtanscolor");
  gtk_widget_ref (mtanscolor);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mtanscolor", mtanscolor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mtanscolor);
  gtk_container_add (GTK_CONTAINER (mtans_menu), mtanscolor);

  mtanstexture = gtk_menu_item_new_with_label (_("Texture..."));
  gtk_widget_set_name (mtanstexture, "mtanstexture");
  gtk_widget_ref (mtanstexture);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mtanstexture", mtanstexture,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mtanstexture);
  gtk_container_add (GTK_CONTAINER (mtans_menu), mtanstexture);

  mhitan = gtk_menu_item_new_with_label (_("Hilighted tan"));
  gtk_widget_set_name (mhitan, "mhitan");
  gtk_widget_ref (mhitan);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mhitan", mhitan,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mhitan);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), mhitan);

  mhitan_menu = gtk_menu_new ();
  gtk_widget_set_name (mhitan_menu, "mhitan_menu");
  gtk_widget_ref (mhitan_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mhitan_menu", mhitan_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (mhitan), mhitan_menu);
  mhitan_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (mhitan_menu));

  mhighcolor = gtk_menu_item_new_with_label (_("Color..."));
  gtk_widget_set_name (mhighcolor, "mhighcolor");
  gtk_widget_ref (mhighcolor);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mhighcolor", mhighcolor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mhighcolor);
  gtk_container_add (GTK_CONTAINER (mhitan_menu), mhighcolor);

  mhightexture = gtk_menu_item_new_with_label (_("Texture..."));
  gtk_widget_set_name (mhightexture, "mhightexture");
  gtk_widget_ref (mhightexture);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mhightexture", mhightexture,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mhightexture);
  gtk_container_add (GTK_CONTAINER (mhitan_menu), mhightexture);

  mbg = gtk_menu_item_new_with_label (_("Background"));
  gtk_widget_set_name (mbg, "mbg");
  gtk_widget_ref (mbg);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mbg", mbg,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mbg);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), mbg);

  mbg_menu = gtk_menu_new ();
  gtk_widget_set_name (mbg_menu, "mbg_menu");
  gtk_widget_ref (mbg_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mbg_menu", mbg_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (mbg), mbg_menu);
  mbg_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (mbg_menu));

  mbgcolor = gtk_menu_item_new_with_label (_("Color..."));
  gtk_widget_set_name (mbgcolor, "mbgcolor");
  gtk_widget_ref (mbgcolor);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mbgcolor", mbgcolor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mbgcolor);
  gtk_container_add (GTK_CONTAINER (mbg_menu), mbgcolor);

  mbgtexture = gtk_menu_item_new_with_label (_("Texture..."));
  gtk_widget_set_name (mbgtexture, "mbgtexture");
  gtk_widget_ref (mbgtexture);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mbgtexture", mbgtexture,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mbgtexture);
  gtk_container_add (GTK_CONTAINER (mbg_menu), mbgtexture);

  mhlpoutcolor = gtk_menu_item_new_with_label (_("Outline help color..."));
  gtk_widget_set_name (mhlpoutcolor, "mhlpoutcolor");
  gtk_widget_ref (mhlpoutcolor);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mhlpoutcolor", mhlpoutcolor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mhlpoutcolor);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), mhlpoutcolor);

  s_parateur1 = gtk_menu_item_new ();
  gtk_widget_set_name (s_parateur1, "s_parateur1");
  gtk_widget_ref (s_parateur1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "s_parateur1", s_parateur1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (s_parateur1);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), s_parateur1);
  gtk_widget_set_sensitive (s_parateur1, FALSE);

  msilcolor = gtk_menu_item_new_with_label (_("Silhouette color..."));
  gtk_widget_set_name (msilcolor, "msilcolor");
  gtk_widget_ref (msilcolor);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "msilcolor", msilcolor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (msilcolor);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), msilcolor);

  msilbgcolor = gtk_menu_item_new_with_label (_("Silhouette background..."));
  gtk_widget_set_name (msilbgcolor, "msilbgcolor");
  gtk_widget_ref (msilbgcolor);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "msilbgcolor", msilbgcolor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (msilbgcolor);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), msilbgcolor);

  msilbgcol2 = gtk_menu_item_new_with_label (_("Solved figure bg..."));
  gtk_widget_set_name (msilbgcol2, "msilbgcol2");
  gtk_widget_ref (msilbgcol2);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "msilbgcol2", msilbgcol2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (msilbgcol2);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), msilbgcol2);

  mhlptancolor = gtk_menu_item_new_with_label (_("Help tan color..."));
  gtk_widget_set_name (mhlptancolor, "mhlptancolor");
  gtk_widget_ref (mhlptancolor);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mhlptancolor", mhlptancolor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mhlptancolor);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), mhlptancolor);

  s_parateur2 = gtk_menu_item_new ();
  gtk_widget_set_name (s_parateur2, "s_parateur2");
  gtk_widget_ref (s_parateur2);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "s_parateur2", s_parateur2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (s_parateur2);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), s_parateur2);
  gtk_widget_set_sensitive (s_parateur2, FALSE);

  imsize = gtk_menu_item_new_with_label (_("Tans size"));
  gtk_widget_set_name (imsize, "imsize");
  gtk_widget_ref (imsize);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "imsize", imsize,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (imsize);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), imsize);

  imsize_menu = gtk_menu_new ();
  gtk_widget_set_name (imsize_menu, "imsize_menu");
  gtk_widget_ref (imsize_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "imsize_menu", imsize_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (imsize), imsize_menu);
  imsize_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (imsize_menu));

  msizinc = gtk_menu_item_new_with_label (_("Increase"));
  gtk_widget_set_name (msizinc, "msizinc");
  gtk_widget_ref (msizinc);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "msizinc", msizinc,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (msizinc);
  gtk_container_add (GTK_CONTAINER (imsize_menu), msizinc);

  msizdec = gtk_menu_item_new_with_label (_("Decrease"));
  gtk_widget_set_name (msizdec, "msizdec");
  gtk_widget_ref (msizdec);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "msizdec", msizdec,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (msizdec);
  gtk_container_add (GTK_CONTAINER (imsize_menu), msizdec);

  maccuracy = gtk_menu_item_new_with_label (_("Accuracy"));
  gtk_widget_set_name (maccuracy, "maccuracy");
  gtk_widget_ref (maccuracy);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "maccuracy", maccuracy,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (maccuracy);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), maccuracy);

  maccuracy_menu = gtk_menu_new ();
  gtk_widget_set_name (maccuracy_menu, "maccuracy_menu");
  gtk_widget_ref (maccuracy_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "maccuracy_menu", maccuracy_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (maccuracy), maccuracy_menu);
  maccuracy_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (maccuracy_menu));

  maccuracy1 = gtk_radio_menu_item_new_with_label (accgrp_group, _("High"));
  accgrp_group = gtk_radio_menu_item_group (GTK_RADIO_MENU_ITEM (maccuracy1));
  gtk_widget_set_name (maccuracy1, "maccuracy1");
  gtk_widget_ref (maccuracy1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "maccuracy1", maccuracy1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (maccuracy1);
  gtk_container_add (GTK_CONTAINER (maccuracy_menu), maccuracy1);

  maccuracy2 = gtk_radio_menu_item_new_with_label (accgrp_group, _("Medium"));
  accgrp_group = gtk_radio_menu_item_group (GTK_RADIO_MENU_ITEM (maccuracy2));
  gtk_widget_set_name (maccuracy2, "maccuracy2");
  gtk_widget_ref (maccuracy2);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "maccuracy2", maccuracy2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (maccuracy2);
  gtk_container_add (GTK_CONTAINER (maccuracy_menu), maccuracy2);

  maccuracy3 = gtk_radio_menu_item_new_with_label (accgrp_group, _("Low"));
  accgrp_group = gtk_radio_menu_item_group (GTK_RADIO_MENU_ITEM (maccuracy3));
  gtk_widget_set_name (maccuracy3, "maccuracy3");
  gtk_widget_ref (maccuracy3);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "maccuracy3", maccuracy3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (maccuracy3);
  gtk_container_add (GTK_CONTAINER (maccuracy_menu), maccuracy3);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (maccuracy3), TRUE);

  rotstp = gtk_menu_item_new_with_label (_("Rotation"));
  gtk_widget_set_name (rotstp, "rotstp");
  gtk_widget_ref (rotstp);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "rotstp", rotstp,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rotstp);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), rotstp);

  rotstp_menu = gtk_menu_new ();
  gtk_widget_set_name (rotstp_menu, "rotstp_menu");
  gtk_widget_ref (rotstp_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "rotstp_menu", rotstp_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (rotstp), rotstp_menu);
  rotstp_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (rotstp_menu));

  mrotcont = gtk_radio_menu_item_new_with_label (rotgrp_group, _("Continuous"));
  rotgrp_group = gtk_radio_menu_item_group (GTK_RADIO_MENU_ITEM (mrotcont));
  gtk_widget_set_name (mrotcont, "mrotcont");
  gtk_widget_ref (mrotcont);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mrotcont", mrotcont,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mrotcont);
  gtk_container_add (GTK_CONTAINER (rotstp_menu), mrotcont);

  mrotstp = gtk_radio_menu_item_new_with_label (rotgrp_group, _("Step by step"));
  rotgrp_group = gtk_radio_menu_item_group (GTK_RADIO_MENU_ITEM (mrotstp));
  gtk_widget_set_name (mrotstp, "mrotstp");
  gtk_widget_ref (mrotstp);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mrotstp", mrotstp,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mrotstp);
  gtk_container_add (GTK_CONTAINER (rotstp_menu), mrotstp);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (mrotstp), TRUE);

  separator1 = gtk_menu_item_new ();
  gtk_widget_set_name (separator1, "separator1");
  gtk_widget_ref (separator1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "separator1", separator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  mfigfile = gtk_menu_item_new_with_label (_("Figures file..."));
  gtk_widget_set_name (mfigfile, "mfigfile");
  gtk_widget_ref (mfigfile);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mfigfile", mfigfile,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mfigfile);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), mfigfile);

  s_parateur3 = gtk_menu_item_new ();
  gtk_widget_set_name (s_parateur3, "s_parateur3");
  gtk_widget_ref (s_parateur3);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "s_parateur3", s_parateur3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (s_parateur3);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), s_parateur3);
  gtk_widget_set_sensitive (s_parateur3, FALSE);

  msaveconf = gtk_menu_item_new_with_label (_("Save config"));
  gtk_widget_set_name (msaveconf, "msaveconf");
  gtk_widget_ref (msaveconf);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "msaveconf", msaveconf,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (msaveconf);
  gtk_container_add (GTK_CONTAINER (mprefs_menu), msaveconf);

  mmisc = gtk_menu_item_new_with_label (_("Misc."));
  gtk_widget_set_name (mmisc, "mmisc");
  gtk_widget_ref (mmisc);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mmisc", mmisc,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mmisc);
  gtk_container_add (GTK_CONTAINER (menubar1), mmisc);

  mmisc_menu = gtk_menu_new ();
  gtk_widget_set_name (mmisc_menu, "mmisc_menu");
  gtk_widget_ref (mmisc_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mmisc_menu", mmisc_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (mmisc), mmisc_menu);
  mmisc_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (mmisc_menu));

  mabout = gtk_menu_item_new_with_label (_("About..."));
  gtk_widget_set_name (mabout, "mabout");
  gtk_widget_ref (mabout);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mabout", mabout,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mabout);
  gtk_container_add (GTK_CONTAINER (mmisc_menu), mabout);

  mhelp = gtk_menu_item_new_with_label (_("Help..."));
  gtk_widget_set_name (mhelp, "mhelp");
  gtk_widget_ref (mhelp);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mhelp", mhelp,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mhelp);
  gtk_container_add (GTK_CONTAINER (mmisc_menu), mhelp);

  sep17 = gtk_menu_item_new ();
  gtk_widget_set_name (sep17, "sep17");
  gtk_widget_ref (sep17);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "sep17", sep17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sep17);
  gtk_container_add (GTK_CONTAINER (mmisc_menu), sep17);
  gtk_widget_set_sensitive (sep17, FALSE);

  mclrstat = gtk_menu_item_new_with_label (_("Clear figure status"));
  gtk_widget_set_name (mclrstat, "mclrstat");
  gtk_widget_ref (mclrstat);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mclrstat", mclrstat,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mclrstat);
  gtk_container_add (GTK_CONTAINER (mmisc_menu), mclrstat);

  mclrall = gtk_menu_item_new_with_label (_("Clear all figures status"));
  gtk_widget_set_name (mclrall, "mclrall");
  gtk_widget_ref (mclrall);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mclrall", mclrall,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mclrall);
  gtk_container_add (GTK_CONTAINER (mmisc_menu), mclrall);

  table1 = gtk_table_new (3, 4, TRUE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, TRUE, TRUE, 0);

  aspectframe1 = gtk_aspect_frame_new (NULL, 0.5, 0.5, 1, FALSE);
  gtk_widget_set_name (aspectframe1, "aspectframe1");
  gtk_widget_ref (aspectframe1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "aspectframe1", aspectframe1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (aspectframe1);
  gtk_table_attach (GTK_TABLE (table1), aspectframe1, 0, 3, 0, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  wdrawareagrande = gtk_drawing_area_new ();
  gtk_widget_set_name (wdrawareagrande, "wdrawareagrande");
  gtk_widget_ref (wdrawareagrande);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "wdrawareagrande", wdrawareagrande,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (wdrawareagrande);
  gtk_container_add (GTK_CONTAINER (aspectframe1), wdrawareagrande);
  gtk_widget_set_events (wdrawareagrande, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK | GDK_STRUCTURE_MASK);

  aspectframe2 = gtk_aspect_frame_new (NULL, 0.5, 0.5, 1, TRUE);
  gtk_widget_set_name (aspectframe2, "aspectframe2");
  gtk_widget_ref (aspectframe2);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "aspectframe2", aspectframe2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (aspectframe2);
  gtk_table_attach (GTK_TABLE (table1), aspectframe2, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  wdrawareapetite = gtk_drawing_area_new ();
  gtk_widget_set_name (wdrawareapetite, "wdrawareapetite");
  gtk_widget_ref (wdrawareapetite);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "wdrawareapetite", wdrawareapetite,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (wdrawareapetite);
  gtk_container_add (GTK_CONTAINER (aspectframe2), wdrawareapetite);
  gtk_widget_set_events (wdrawareapetite, GDK_EXPOSURE_MASK | GDK_STRUCTURE_MASK);

  vbox2 = gtk_vbox_new (FALSE, 3);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_table_attach (GTK_TABLE (table1), vbox2, 3, 4, 1, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 3);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, FALSE, FALSE, 0);

  label2 = gtk_label_new (_("Figure "));
  gtk_widget_set_name (label2, "label2");
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, TRUE, TRUE, 0);

  bfignr_adj = gtk_adjustment_new (1000, 0, 1000, 1, 10, 10);
  bfignr = gtk_spin_button_new (GTK_ADJUSTMENT (bfignr_adj), 1, 0);
  gtk_widget_set_name (bfignr, "bfignr");
  gtk_widget_ref (bfignr);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "bfignr", bfignr,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bfignr);
  gtk_box_pack_start (GTK_BOX (hbox1), bfignr, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (bfignr), TRUE);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (bfignr), TRUE);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator2, "hseparator2");
  gtk_widget_ref (hseparator2);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "hseparator2", hseparator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator2, FALSE, FALSE, 0);

  bunsel = gtk_button_new_with_label (_("Unselect tan"));
  gtk_widget_set_name (bunsel, "bunsel");
  gtk_widget_ref (bunsel);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "bunsel", bunsel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bunsel);
  gtk_box_pack_start (GTK_BOX (vbox2), bunsel, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (bunsel, GTK_CAN_FOCUS);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_ref (hseparator1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "hseparator1", hseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator1, FALSE, FALSE, 0);

  bhlptan = gtk_button_new_with_label (_("Show a tan"));
  gtk_widget_set_name (bhlptan, "bhlptan");
  gtk_widget_ref (bhlptan);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "bhlptan", bhlptan,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bhlptan);
  gtk_box_pack_start (GTK_BOX (vbox2), bhlptan, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (bhlptan, GTK_CAN_FOCUS);

  bhlpout = gtk_button_new_with_label (_("Show outline"));
  gtk_widget_set_name (bhlpout, "bhlpout");
  gtk_widget_ref (bhlpout);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "bhlpout", bhlpout,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bhlpout);
  gtk_box_pack_start (GTK_BOX (vbox2), bhlpout, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (bhlpout, GTK_CAN_FOCUS);

  wstatusbar = gtk_statusbar_new ();
  gtk_widget_set_name (wstatusbar, "wstatusbar");
  gtk_widget_ref (wstatusbar);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "wstatusbar", wstatusbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (wstatusbar);
  gtk_box_pack_start (GTK_BOX (vbox1), wstatusbar, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (mainwindow), "destroy",
                      GTK_SIGNAL_FUNC (on_mainwindow_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mquit), "activate",
                      GTK_SIGNAL_FUNC (on_mquit_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mtanscolor), "activate",
                      GTK_SIGNAL_FUNC (on_mtanscolor_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mtanstexture), "activate",
                      GTK_SIGNAL_FUNC (on_mtanstexture_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mhighcolor), "activate",
                      GTK_SIGNAL_FUNC (on_mhighcolor_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mhightexture), "activate",
                      GTK_SIGNAL_FUNC (on_mhightexture_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mbgcolor), "activate",
                      GTK_SIGNAL_FUNC (on_mbgcolor_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mbgtexture), "activate",
                      GTK_SIGNAL_FUNC (on_mbgtexture_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mhlpoutcolor), "activate",
                      GTK_SIGNAL_FUNC (on_mhlpoutcolor_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (msilcolor), "activate",
                      GTK_SIGNAL_FUNC (on_msilcolor_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (msilbgcolor), "activate",
                      GTK_SIGNAL_FUNC (on_msilbgcolor_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (msilbgcol2), "activate",
                      GTK_SIGNAL_FUNC (on_msilbgcol2_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mhlptancolor), "activate",
                      GTK_SIGNAL_FUNC (on_mhlptancolor_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (msizinc), "activate",
                      GTK_SIGNAL_FUNC (on_msizinc_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (msizdec), "activate",
                      GTK_SIGNAL_FUNC (on_msizdec_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (maccuracy1), "activate",
                      GTK_SIGNAL_FUNC (on_maccuracy1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (maccuracy2), "activate",
                      GTK_SIGNAL_FUNC (on_maccuracy2_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (maccuracy3), "activate",
                      GTK_SIGNAL_FUNC (on_maccuracy3_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mrotcont), "activate",
                      GTK_SIGNAL_FUNC (on_mrotcont_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mrotstp), "activate",
                      GTK_SIGNAL_FUNC (on_mrotstp_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mfigfile), "activate",
                      GTK_SIGNAL_FUNC (on_mfigfile_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (msaveconf), "activate",
                      GTK_SIGNAL_FUNC (on_msaveconf_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mabout), "activate",
                      GTK_SIGNAL_FUNC (on_mabout_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mhelp), "activate",
                      GTK_SIGNAL_FUNC (on_mhelp_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mclrstat), "activate",
                      GTK_SIGNAL_FUNC (on_mclrstat_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mclrall), "activate",
                      GTK_SIGNAL_FUNC (on_mclrall_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (wdrawareagrande), "expose_event",
                      GTK_SIGNAL_FUNC (on_wdrawareagrande_expose_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (wdrawareagrande), "configure_event",
                      GTK_SIGNAL_FUNC (on_wdrawareagrande_configure_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (wdrawareagrande), "button_press_event",
                      GTK_SIGNAL_FUNC (on_wdrawareagrande_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (wdrawareagrande), "button_release_event",
                      GTK_SIGNAL_FUNC (on_wdrawareagrande_button_release_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (wdrawareagrande), "motion_notify_event",
                      GTK_SIGNAL_FUNC (on_wdrawareagrande_motion_notify_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (wdrawareapetite), "configure_event",
                      GTK_SIGNAL_FUNC (on_wdrawareapetite_configure_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (wdrawareapetite), "expose_event",
                      GTK_SIGNAL_FUNC (on_wdrawareapetite_expose_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bfignr), "changed",
                      GTK_SIGNAL_FUNC (on_bfignr_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bunsel), "clicked",
                      GTK_SIGNAL_FUNC (on_bunsel_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bhlptan), "clicked",
                      GTK_SIGNAL_FUNC (on_bhlptan_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bhlpout), "clicked",
                      GTK_SIGNAL_FUNC (on_bhlpout_clicked),
                      NULL);

  return mainwindow;
}

GtkWidget*
create_fileselectwindow (void)
{
  GtkWidget *fileselectwindow;
  GtkWidget *bfsok;
  GtkWidget *bfscancel;

  fileselectwindow = gtk_file_selection_new (_("Select a file"));
  gtk_widget_set_name (fileselectwindow, "fileselectwindow");
  gtk_object_set_data (GTK_OBJECT (fileselectwindow), "fileselectwindow", fileselectwindow);
  gtk_container_set_border_width (GTK_CONTAINER (fileselectwindow), 10);
  gtk_window_set_modal (GTK_WINDOW (fileselectwindow), TRUE);
  gtk_file_selection_hide_fileop_buttons (GTK_FILE_SELECTION (fileselectwindow));

  bfsok = GTK_FILE_SELECTION (fileselectwindow)->ok_button;
  gtk_widget_set_name (bfsok, "bfsok");
  gtk_object_set_data (GTK_OBJECT (fileselectwindow), "bfsok", bfsok);
  gtk_widget_show (bfsok);
  GTK_WIDGET_SET_FLAGS (bfsok, GTK_CAN_DEFAULT);

  bfscancel = GTK_FILE_SELECTION (fileselectwindow)->cancel_button;
  gtk_widget_set_name (bfscancel, "bfscancel");
  gtk_object_set_data (GTK_OBJECT (fileselectwindow), "bfscancel", bfscancel);
  gtk_widget_show (bfscancel);
  GTK_WIDGET_SET_FLAGS (bfscancel, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (fileselectwindow), "delete_event",
                      GTK_SIGNAL_FUNC (on_fileselectwindow_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bfsok), "clicked",
                      GTK_SIGNAL_FUNC (on_bfsok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bfscancel), "clicked",
                      GTK_SIGNAL_FUNC (on_bfscancel_clicked),
                      NULL);

  return fileselectwindow;
}

GtkWidget*
create_colorselectwindow (void)
{
  GtkWidget *colorselectwindow;
  GtkWidget *bcsok;
  GtkWidget *bcscancel;
  GtkWidget *help_button1;

  colorselectwindow = gtk_color_selection_dialog_new (_("Select color"));
  gtk_widget_set_name (colorselectwindow, "colorselectwindow");
  gtk_object_set_data (GTK_OBJECT (colorselectwindow), "colorselectwindow", colorselectwindow);
  gtk_container_set_border_width (GTK_CONTAINER (colorselectwindow), 10);
  gtk_window_set_modal (GTK_WINDOW (colorselectwindow), TRUE);

  bcsok = GTK_COLOR_SELECTION_DIALOG (colorselectwindow)->ok_button;
  gtk_widget_set_name (bcsok, "bcsok");
  gtk_object_set_data (GTK_OBJECT (colorselectwindow), "bcsok", bcsok);
  gtk_widget_show (bcsok);
  GTK_WIDGET_SET_FLAGS (bcsok, GTK_CAN_DEFAULT);

  bcscancel = GTK_COLOR_SELECTION_DIALOG (colorselectwindow)->cancel_button;
  gtk_widget_set_name (bcscancel, "bcscancel");
  gtk_object_set_data (GTK_OBJECT (colorselectwindow), "bcscancel", bcscancel);
  gtk_widget_show (bcscancel);
  GTK_WIDGET_SET_FLAGS (bcscancel, GTK_CAN_DEFAULT);

  help_button1 = GTK_COLOR_SELECTION_DIALOG (colorselectwindow)->help_button;
  gtk_widget_set_name (help_button1, "help_button1");
  gtk_object_set_data (GTK_OBJECT (colorselectwindow), "help_button1", help_button1);
  gtk_widget_show (help_button1);
  GTK_WIDGET_SET_FLAGS (help_button1, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (colorselectwindow), "delete_event",
                      GTK_SIGNAL_FUNC (on_colorselectwindow_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bcsok), "clicked",
                      GTK_SIGNAL_FUNC (on_bcsok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bcscancel), "clicked",
                      GTK_SIGNAL_FUNC (on_bcscancel_clicked),
                      NULL);

  return colorselectwindow;
}

GtkWidget*
create_aboutwindow (void)
{
  GtkWidget *aboutwindow;
  GtkWidget *dialog_vbox1;
  GtkWidget *label1;
  GtkWidget *dialog_action_area1;
  GtkWidget *babclose;

  aboutwindow = gtk_dialog_new ();
  gtk_widget_set_name (aboutwindow, "aboutwindow");
  gtk_object_set_data (GTK_OBJECT (aboutwindow), "aboutwindow", aboutwindow);
  gtk_window_set_title (GTK_WINDOW (aboutwindow), _("About gTans"));
  gtk_window_set_modal (GTK_WINDOW (aboutwindow), TRUE);
  gtk_window_set_policy (GTK_WINDOW (aboutwindow), TRUE, TRUE, FALSE);

  dialog_vbox1 = GTK_DIALOG (aboutwindow)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_object_set_data (GTK_OBJECT (aboutwindow), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  label1 = gtk_label_new (_("gTans v1.2\nhttp://gtans.sourceforge.net\n\nPhilippe Banwarth\nbwt@altern.org\n\nPlease send me\ncomments, bug reports..."));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (aboutwindow), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), label1, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label1), 5, 5);

  dialog_action_area1 = GTK_DIALOG (aboutwindow)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_object_set_data (GTK_OBJECT (aboutwindow), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  babclose = gtk_button_new_with_label (_("Close"));
  gtk_widget_set_name (babclose, "babclose");
  gtk_widget_ref (babclose);
  gtk_object_set_data_full (GTK_OBJECT (aboutwindow), "babclose", babclose,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (babclose);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), babclose, FALSE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (aboutwindow), "destroy",
                      GTK_SIGNAL_FUNC (on_aboutwindow_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (babclose), "clicked",
                      GTK_SIGNAL_FUNC (on_babclose_clicked),
                      NULL);

  return aboutwindow;
}

GtkWidget*
create_helpwindow (void)
{
  GtkWidget *helpwindow;
  GtkWidget *dialog_vbox2;
  GtkWidget *scrolledwindow1;
  GtkWidget *whltext;
  GtkWidget *dialog_action_area2;
  GtkWidget *bhlclose;

  helpwindow = gtk_dialog_new ();
  gtk_widget_set_name (helpwindow, "helpwindow");
  gtk_object_set_data (GTK_OBJECT (helpwindow), "helpwindow", helpwindow);
  gtk_window_set_title (GTK_WINDOW (helpwindow), _("gTans help"));
  gtk_window_set_modal (GTK_WINDOW (helpwindow), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (helpwindow), 470, 400);

  dialog_vbox2 = GTK_DIALOG (helpwindow)->vbox;
  gtk_widget_set_name (dialog_vbox2, "dialog_vbox2");
  gtk_object_set_data (GTK_OBJECT (helpwindow), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (helpwindow), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  whltext = gtk_text_new (NULL, NULL);
  gtk_widget_set_name (whltext, "whltext");
  gtk_widget_ref (whltext);
  gtk_object_set_data_full (GTK_OBJECT (helpwindow), "whltext", whltext,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (whltext);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), whltext);

  dialog_action_area2 = GTK_DIALOG (helpwindow)->action_area;
  gtk_widget_set_name (dialog_action_area2, "dialog_action_area2");
  gtk_object_set_data (GTK_OBJECT (helpwindow), "dialog_action_area2", dialog_action_area2);
  gtk_widget_show (dialog_action_area2);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area2), 10);

  bhlclose = gtk_button_new_with_label (_("Close"));
  gtk_widget_set_name (bhlclose, "bhlclose");
  gtk_widget_ref (bhlclose);
  gtk_object_set_data_full (GTK_OBJECT (helpwindow), "bhlclose", bhlclose,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bhlclose);
  gtk_box_pack_start (GTK_BOX (dialog_action_area2), bhlclose, FALSE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (helpwindow), "destroy",
                      GTK_SIGNAL_FUNC (on_helpwindow_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bhlclose), "clicked",
                      GTK_SIGNAL_FUNC (on_bhlclose_clicked),
                      NULL);

  return helpwindow;
}

