/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainwindow (void);
GtkWidget* create_fileselectwindow (void);
GtkWidget* create_colorselectwindow (void);
GtkWidget* create_aboutwindow (void);
GtkWidget* create_helpwindow (void);
